use_frameworks!

target 'DKViewModel_Example' do
  pod 'DKViewModel', :path => '../'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MBProgressHUD'

  target 'DKViewModel_Tests' do
    inherit! :search_paths

    
  end
end
